services:
  full_service:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SERVICE_ROLE=full
      - FULL_URL=http://83.217.221.87:8000
      - AUTH_URL=http://83.217.221.87:8001
      - COMMENTS_URL=http://83.217.221.87:8002
    container_name: full_service
    networks:
      - microservices_net
    hostname: full_service

  auth_service:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - SERVICE_ROLE=auth
      - FULL_URL=http://83.217.221.87:8000
      - AUTH_URL=http://83.217.221.87:8001
      - COMMENTS_URL=http://83.217.221.87:8002
    container_name: auth_service
    networks:
      - microservices_net
    hostname: auth_service

  comments_service:
    build: .
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    environment:
      - SERVICE_ROLE=comments
      - FULL_URL=http://83.217.221.87:8000
      - AUTH_URL=http://83.217.221.87:8001
      - COMMENTS_URL=http://83.217.221.87:8002
    container_name: comments_service
    networks:
      - microservices_net
    hostname: comments_service

networks:
  microservices_net:
    driver: bridge
