services:
  - type: web
    name: lamborgini-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lamborgini-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: SERVICE_ROLE
        value: full
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"

databases:
  - name: lamborgini-db
    plan: free
