# Generated by Django 6.0.3 on 2026-03-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('ticket_type', models.CharField(choices=[('обычный', 'Обычный'), ('вип', 'ВИП')], max_length=20, verbose_name='Тип билета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Заявка на билет',
                'verbose_name_plural': 'Заявки на билеты',
            },
        ),
    ]
